global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "node"
    static_configs:
      - targets: ["10.182.0.2:9100"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["34.16.192.36:9093"] 

rule_files:
  - './alert.rules.yml'
 
